# Auto-generated data for faculty
faculty_records = [
    (1, 'Mr. M. L. Thorat', 'mlthorat@gmail.com', '**********', 1, 'faculty123', 'default_avatar.png'),
    (2, 'Mr. N. J. Runwal', 'njrunwal@gmail.com', '**********', 1, 'faculty123', 'default_avatar.png'),
    (3, 'Mr. R. A. Solunke', 'rasolunke@gmail.com', '**********', 1, 'faculty123', 'default_avatar.png'),
    (4, 'Dr. S. C. Kulkarni', 'sckulkarni@gmail.com', '**********', 1, 'faculty123', 'default_avatar.png'),
    (5, 'Mr. K. M. Patil', 'kmpatil@gmail.com', '**********', 1, 'faculty123', 'default_avatar.png'),
    (6, 'Mr. Sudhir S. Nikam', 'sudhirnikam@gmail.com', '**********', 2, 'faculty123', 'default_avatar.png'),
    (7, ' Mrs. Surekha S. Patil', 'surekha@gmail.com', '**********', 2, 'faculty123', 'default_avatar.png'),
    (8, 'Ms. Sneha S. Bhende', 'snehabhende@gmail.com', '**********', 2, 'faculty123', 'default_avatar.png'),
    (9, 'Ms. Pooja Sonawane', 'pooja@gmail.com', '**********', 2, 'faculty123', 'default_avatar.png'),
    (10, 'Mr. Suraj W. Jagtap', 'suraj@gmail.com', '**********', 2, 'faculty123', 'default_avatar.png'),
    (11, 'Ms. Priyanka Jadhav', 'priyanka@gmail.com', '**********', 3, 'faculty123', 'default_avatar.png'),
    (12, 'Mrs. Durga Sawant', 'durgasawant@gmail.com', '**********', 3, 'faculty123', 'default_avatar.png'),
    (13, 'Mrs. Swati Patange', 'swati@gmail.com', '**********', 3, 'faculty123', 'default_avatar.png'),
    (14, 'Prof. Nandini Lambole', 'nandini@gmail.com', '**********', 3, 'faculty123', 'default_avatar.png'),
    (15, 'Mrs. Priyanka Waghmare', 'priyankawaghmare@gmail.com', '**********', 3, 'faculty123', 'default_avatar.png'),
    (16, 'Ms. Jaitee Bankar', 'jaiteebankar@gmail.com', '**********', 4, 'faculty123', 'default_avatar.png'),
    (17, 'Mr. Vishal Abhong', 'vishalabhong@gmail.com', '**********', 4, 'faculty123', 'default_avatar.png'),
    (18, 'Mrs. Suvarna Potdukhe', 'suvarnapotdukhe@gmail.com', '**********', 4, 'faculty123', 'default_avatar.png'),
    (19, 'Mrs. Sweta Kale', 'swetakale@gmail.com', '**********', 4, 'faculty123', 'default_avatar.png'),
    (20, 'Mrs. Pooja Sonwane', 'poojasonwane@gmail.com', '**********', 4, 'faculty123', 'default_avatar.png'),
    (21, 'Mr. Bhupesh Shukla', 'bhupeshshukla@gmail.com', '**********', 5, 'faculty123', 'default_avatar.png'),
    (22, 'Mrs. Shalini', 'shalini@gmail.com', '**********', 5, 'faculty123', 'default_avatar.png'),
    (23, 'Ms. Shrushti Kadam', 'shrushtikadam@gmail.com', '**********', 5, 'faculty123', 'default_avatar.png'),
    (24, 'Dr. Balram Goyal', 'balramgoyal@gmail.com', '**********', 5, 'faculty123', 'default_avatar.png'),
    (25, 'Mrs. Swati Kshirsagar', 'swatikshirsagar@gmail.com', '**********', 5, 'faculty123', 'default_avatar.png'),
]
